### ISSUE TITLE
Trades are not shown in "trades.py" report 

### ISSUE THREAD

**Issue by mkuzmentsov** [valory-xyz/trader-quickstart#318] opened 2024-07-05 05:48 UTC
My service instance had not been executing trades for a while (week or so), it got funded recently, but trades are not showing, even though I see trades are being executed regularly.

Here's the report:
```
$ poetry run python ../trades.py --creator 0x74D2b585a46279b4fa9fEEAE001efc972726C709
Updating the local Mech events database. This may take a while.
             Event: Request
    Sender address: 0x74D2b585a46279b4fa9fEEAE001efc972726C709

------
Trades
------

--------------------------
Summary (per market state)
--------------------------

Safe address:    0x74D2b585a46279b4fa9fEEAE001efc972726C709
Address balance: 13.79 xDAI
Token balance:   2.79 WxDAI

                        Open       Pending    Finalizing   Arbitrating        Closed       Unknown         TOTAL
----------------------------------------------------------------------------------------------------------------
Num_trades                 0             0             0             0             0             0             0
Winner_trades              0             0             0             0             0             0             0
Num_redeemed               0             0             0             0             0             0             0
Mech_calls                 0             0             0             0             0             0           108
Investment         0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI
Fees               0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI
Mech_fees          0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     1.08 xDAI
Earnings           0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI
Net_earnings       0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI    -1.08 xDAI
Redemptions        0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI     0.00 xDAI
ROI                0.00 %        0.00 %        0.00 %        0.00 %        0.00 %        0.00 %     -100.00 %  

```

How do I get them showing again?

**Comment by jmoreira-valory** [comment] 2024-08-22 13:34
@mkuzmentsov Is this issue resolved with latest releases? If not, can you provide your service ID?

**Comment by jmoreira-valory** [comment] 2024-08-25 11:04
@mkuzmentsov I have verified that it works as
`cd trader; poetry run python ../trades.py --creator 0x74D2b585a46279b4fa9fEEAE001efc972726C709`
Trades table seems to be filled correctly. I assume the issue is already resolved. If this is not the case, please feel free to reopen the issue and provide additional data (OS, Python version, etc.)

FYI: Note that your service is not currently running in a staking program (Coastal program is now deprecated). Please pull latest changes on the repository and choose an appropriate staking contract if you wish:

```
./stop_service.sh
cd trader; poetry run python ../scripts/choose_staking.py --reset; cd ..
```

**Closed by jmoreira-valory** 2024-08-25 11:04 UTC
