### ISSUE TITLE
run_service.sh with staking flag stops unexpectedly

### ISSUE THREAD

**Issue by dagacha** [valory-xyz/trader-quickstart#97] opened 2023-11-15 11:00 UTC
```
parallels@ubuntu-linux-22-04-02-desktop:~/work/staking-service/trader-quickstart$ ./run_service.sh --with-staking

---------------
 Trader runner 
---------------

This script will assist you in setting up and running the Trader service (https://github.com/valory-xyz/trader).

Checking the provided RCP...
RPC checks passed.

Detected an existing trader repo. Using this one...
Please stop and manually delete the trader repo if you updated the service's version (v0.9.2.post1)!
You can run the following command, or continue with the pre-existing version of the service:
rm -r trader
Installing dependencies from lock file

No dependencies to install or update

Installing the current project: trader (0.1.0)
[2023-11-15 10:56:22,794][INFO] Performing sync @ /home/parallels/work/staking-service/trader-quickstart/trader/packages
[2023-11-15 10:56:22,795][INFO] Checking third party packages.
[2023-11-15 10:56:22,813][INFO] No package was updated.

-----------------------------------------
Checking Autonolas Protocol service state
-----------------------------------------

Your currently minted on-chain service (id 198) mismatches the fetched trader service (v0.9.2.post1):
  - Local service hash (v0.9.2.post1): bafybeieh2ttygh6rkfuxvqhvpyahar2dstwlqe64xwrb4q4f2ukcnrcgaq
  - On-chain service hash (id 198): bafybeidru4qhpp7wgx2qqkg74rvp7fytvl45bj2iosalwava4j3hhsedjy

This is most likely caused due to an update of the trader service code.
The script will proceed now to update the on-chain service.
The operator and agent addresses need to have enough funds so that the process is not interrupted.

Warning: updating the on-chain may require that your service is unstaked.
Continuing will automatically unstake your service if it is staked, which may effect your staking rewards.
Do you want to continue? [y/N]
y
```

After entering 'y' or 'yes' the script stops without completing the task.

**Comment by jmoreira-valory** [comment] 2023-11-15 11:04
This is a duplicate of https://github.com/valory-xyz/trader-quickstart/issues/94

**Closed** 2023-11-15 11:15 UTC
