### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by dagacha** [valory-xyz/trader-quickstart#222] opened 2024-02-06 12:19 UTC
Running from branch `origin/fix/increase_sleep_duration`the following error is displayed and the `run_service.sh` script stops.

`Service activated succesfully
[Operator] Registering agent instance for on-chain service 241...
Error occured when interacting with chain: Transaction with hash: '0xfd9eda29c0cdb0a6a38a1faa7d0f2381561d7144801676bfb37ed3fcbc3ed524' not found.; 
will retry in 3.0...
Error occured when interacting with chain: Transaction with hash: '0xfd9eda29c0cdb0a6a38a1faa7d0f2381561d7144801676bfb37ed3fcbc3ed524' not found.; 
will retry in 3.0...
Error occured when interacting with chain: Transaction with hash: '0xfd9eda29c0cdb0a6a38a1faa7d0f2381561d7144801676bfb37ed3fcbc3ed524' not found.; 
will retry in 3.0...
Agent instance registered succesfully
[Service owner] Deploying on-chain service 241...
Traceback (most recent call last):
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/bin/autonomy", line 8, in <module>
    sys.exit(cli())
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/click/core.py", line 1126, in __call__
    return self.main(*args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/click/core.py", line 1051, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/click/core.py", line 1393, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/click/decorators.py", line 84, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/click/core.py", line 752, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/autonomy/cli/service.py", line 183, in _deploy
    ServiceHelper(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/autonomy/cli/helpers/chain.py", line 828, in deploy_service
    self.manager.deploy(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/autonomy/chain/service.py", line 452, in deploy
    _deployment_payload, error = get_reuse_multisig_payload(
  File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/autonomy/chain/service.py", line 625, in get_reuse_multisig_payload
    args=[new_owners[0], service_owner, 1],
IndexError: list index out of range
`

**Comment by angrybayblade** [comment] 2024-02-09 06:30
@jmoreira-valory @dagacha The error

```
File "/home/ubuntu/.cache/pypoetry/virtualenvs/trader-A4psh6E9-py3.10/lib/python3.10/site-packages/autonomy/chain/service.py", line 625, in get_reuse_multisig_payload args=[new_owners[0], service_owner, 1], IndexError: list index out of range 
```

is caused by `new_owners` array being empty, which means there was some issue with the registering the instances since the `new_owners` are supposed to be the list of newly registered agent instances, https://github.com/valory-xyz/open-autonomy/blob/7232942059f706a98c6d13d5111a95da24e8dda5/autonomy/chain/service.py#L592

**Comment by angrybayblade** [comment] 2024-02-09 16:30
Closing this since neither me nor @jmoreira-valory can recreate the issue

**Closed by angrybayblade** 2024-02-09 16:30 UTC
Labels: bug
